# .circleci/config.yml
version: 2.1

jobs:
  test-arm-runner:
    machine: true
    resource_class: abhayps/arm64-linux
    steps:
      - checkout
      - run:
          name: Show Architecture
          command: |
            ARCH=$(uname -m)
            echo "Detected architecture: $ARCH"
            if [ "$ARCH" = "aarch64" ]; then
              echo "✅ Running on ARM64 architecture!"
            else
              echo "⚠️ Not running on ARM64!"
              exit 1
            fi

workflows:
  test:
    jobs:
      - test-arm-runner
