# .circleci/config.yml
version: 2.1

jobs:
  test-arm-runner:
    machine: true
    resource_class: abhayps/arm64-linux
    steps:
      - checkout
      - run: echo "✅ Running on SUSE ARM64 runner!"

workflows:
  test:
    jobs:
      - test-arm-runner

