version: 2.1

jobs:
  build-arm:
    machine: true   # Use native VM
    steps:
      - checkout
      - run:
          name: Show Architecture
          command: uname -m
      - run:
          name: Build App
          command: |
            echo "Building app for ARM64..."
            # Add your build commands here

  test-arm:
    machine: true
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            echo "Running tests on ARM64..."
            # Add your test commands here

  docker-build:
    machine: true
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Enable Docker Buildx
          command: |
            docker buildx create --use
            docker buildx inspect --bootstrap
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
      - run:
          name: Build Multi-Arch Docker Image
          command: |
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              -t $DOCKERHUB_USER/demo-app:latest \
              --push .
      - run:
          name: Verify Multi-Arch Image
          command: docker buildx imagetools inspect $DOCKERHUB_USER/demo-app:latest

workflows:
  version: 2
  arm-docker-workflow:
    jobs:
      - build-arm
      - test-arm:
          requires:
            - build-arm
      - docker-build:
          requires:
            - test-arm

